### ISSUE TITLE
there is no catchsegv, which is why I cannot build some packages

### ISSUE THREAD

**Issue by KuKuRuZ1337** [h0tc0d3/arch-packages#12]
After googling catchsegv, I realized that it is in the archlinux glibc 2.33-5 package, but apparently it is not in this repository
is there any way you could fix this situation ? 
it never happened before
![изображение](https://user-images.githubusercontent.com/65289168/149681216-5798e2d2-c593-406c-8503-996149e34a17.png)

**Comment by h0tc0d3** [comment]
From glibc changelog:
> The catchsegv script and associated libSegFault.so shared object have
>   been removed.  There are widely-deployed out-of-process alternatives for
>   catching coredumps and backtraces.
Open bug report in mutter source.
