### ISSUE TITLE
symbol lookup error: /usr/lib/libKF5Package.so.5

### ISSUE THREAD

**Issue by KuKuRuZ1337** [h0tc0d3/arch-packages#13]
![изображение](https://user-images.githubusercontent.com/65289168/154280103-9c332d8b-17cf-4c4c-a06e-cfaeb622a351.png)
I can't use dolphin.
Any suggestions on how to fix it ? 
i found out that archlinux started using glibc 2.35, i immediately installed archlinuxclub
but unfortunately i can't run my favorite file manager

**Comment by h0tc0d3** [comment]
[KuKuRuZ1337](https://github.com/KuKuRuZ1337) try to install kcoreaddons+clang.

**Comment by KuKuRuZ1337** [comment]
![изображение](https://user-images.githubusercontent.com/65289168/154332085-9a37a5dd-c445-476e-920c-a6c391ae3c23.png)

I put the normal version (from vanilla arch) and everything worked!
Thank you very much.
