### ISSUE TITLE
problem with glibc 2.35-11

### ISSUE THREAD

**Issue by KuKuRuZ1337** [h0tc0d3/arch-packages#17]
With glibc 2.34-11 games from steam do not run, both native (eg cs:go, css, cs 1.6, etc.) and windows (eg the first assassin's creed)
But with glibc 2.34-10 no problem (installed from cache), it all works perfectly

**Comment by ptr1337** [comment]
Try to add this patch and rebuild it, I think it should work then:
https://github.com/ptr1337/toolchain/blob/master/glibc/glibc-fix-electron.patch

**Comment by KuKuRuZ1337** [comment]
> Try to add this patch and rebuild it, I think it should work then: https://github.com/ptr1337/toolchain/blob/master/glibc/glibc-fix-electron.patch

https://imgur.com/kGdItkT

Something is not going with this patch
here if anything PKGBUILD: https://termbin.com/9ake
and here's makepkg.conf: https://termbin.com/xjc3

**Comment by ptr1337** [comment]
Compile with GCC. glibc does not work to compile with llvm currently.

Can recommend you to change faster between llvm and gcc setting this into makepkg.conf:

https://github.com/ptr1337/dotfiles/blob/master/config/makepkg.conf#L43

**Comment by KuKuRuZ1337** [comment]
> 



> Compile with GCC. glibc does not work to compile with llvm currently.
> 
> Can recommend you to change faster between llvm and gcc setting this into makepkg.conf:
> 
> https://github.com/ptr1337/dotfiles/blob/master/config/makepkg.conf#L43

https://imgur.com/4sdMST1

I have gcc 12.1.1-1 from archlinux-club
I ended up with an error
here is my makepkg-gcc.conf: https://termbin.com/dwoh

**Comment by ptr1337** [comment]
@KuKuRuZ1337 

Try to disable check at options:
BUILDENV=(!distcc color !ccache !check !sign)

**Comment by h0tc0d3** [comment]
You can make backtrace?

**Comment by h0tc0d3** [comment]
@KuKuRuZ1337 

```
strace program
gdb -q program
run
----crash---
bt full
```

**Comment by KuKuRuZ1337** [comment]
> gdb -q

https://pastebin.com/n8F753GS
https://pastebin.com/SJpYEPE2

**Comment by ptr1337** [comment]
Just a quote from a distro's webpage, the founder is maintaining proton:

`glibc patched with clone3 disabled (fixes CEF compatibility in applications using outdated CEF such as Discord, Steam beta)`

**Comment by h0tc0d3** [comment]
@KuKuRuZ1337 in gdb need enter **run** before **bt full**.
Also I see the problem: 
```
error while loading shared libraries: libtcmalloc_minimal.so.0: cannot open shared object file: No such file or directory
```
Try install `gperftools`

**Comment by KuKuRuZ1337** [comment]
> @KuKuRuZ1337 in gdb need enter **run** before **bt full**. Also I see the problem:
> 
> ```
> error while loading shared libraries: libtcmalloc_minimal.so.0: cannot open shared object file: No such file or directory
> ```
> 


https://pastebin.com/vg5vMTdp

> Try install `gperftools+clang` and `sudo ln -s /usr/lib/libtcmalloc_minimal.so /usr/lib/libtcmalloc_minimal.so.0`

done

**Comment by h0tc0d3** [comment]
@KuKuRuZ1337 `engine_client.so: wrong ELF class: ELFCLASS32` 
Problem with 32 bit. It is difficult to say what is the reason.

**Comment by ptr1337** [comment]
Yes, lib32-glibc needs to be compiled also.

**Comment by h0tc0d3** [comment]
@ptr1337 it's not clone3 problem. clone3 the problem was in 2.34 and is already solved in many packages

**Comment by ptr1337** [comment]
@h0tc0d3 
I dont know, I can apply the patch fine on your's.

**Comment by h0tc0d3** [comment]
@KuKuRuZ1337 try as root ```yes | pacman -Scc && pacman -Syu lib32-glibc```

**Comment by KuKuRuZ1337** [comment]
> @KuKuRuZ1337 `engine_client.so: wrong ELF class: ELFCLASS32` Problem with 32 bit. It is difficult to say what is the reason.

It turns out I ran the wrong file before
I recorded a video of running with glibc 2.35.12 and 2.35.10
https://www.youtube.com/watch?v=x2Xz-LYQLEs
https://pastebin.com/ESTkExQU

> @KuKuRuZ1337 try as root `yes | pacman -Scc && pacman -Syu lib32-glibc`

I did this after I recorded the video, but it doesn't work

**Comment by KuKuRuZ1337** [comment]
@h0tc0d3 
Try adding the patch that ptr1337 above
I got it with GCC, CLANG, or --nocheck parameters and it didn't build without errors
Here it is:
https://github.com/ptr1337/toolchain/blob/master/glibc/glibc-fix-electron.patch

**Comment by h0tc0d3** [comment]
@h0tc0d3 it won't help. I will try to install steam as soon as I finish building chromium.

**Comment by KuKuRuZ1337** [comment]
> @h0tc0d3 it won't help. I will try to install steam as soon as I finish building chromium.

Too bad you're doing a chrome build and not firefox, but whatever.
Thank you for your help.

**Comment by h0tc0d3** [comment]
@h0tc0d3 rust programs is shit. rust is still a raw compiler, often programs pull dependencies that break the build, simd support is very flat, and often breaks. Rust is the most insecure language, programs pull too many dependencies, they can contain backdoors. It is also impossible to edit a dependency package due to their cargo system and checksums, if there is a backdoor or a code error without the author it is not possible to update the package. Often, for the same reason, the assembly of programs breaks. Also, recent versions of rust crash when downloading dependencies due to an unclosed bug in libgit2.

**Comment by ptr1337** [comment]
> @h0tc0d3 Try adding the patch that ptr1337 above I got it with GCC, CLANG, or --nocheck parameters and it didn't build without errors Here it is: https://github.com/ptr1337/toolchain/blob/master/glibc/glibc-fix-electron.patch

did it fix your error ?

**Comment by h0tc0d3** [comment]
@KuKuRuZ1337 please try new `glibc 2.35-14`.

**Comment by KuKuRuZ1337** [comment]
> @KuKuRuZ1337 please try new `glibc 2.35-14`.

![изображение](https://user-images.githubusercontent.com/65289168/168038575-336221b3-ecbf-4777-bdef-7f30e75fb430.png)
Thank you, it works now.
