### ISSUE TITLE
Package repository removed

### ISSUE THREAD

**Issue by h0tc0d3** [h0tc0d3/arch-packages#20]
Due to the fact that someone created a huge and anomalous traffic to the repository. In a couple of hours, hundreds of times more traffic was used than in the past months! It wasn't a package update, it was probably an attack. Package updates cannot generate this kind of traffic. The cloud billed me, it was decided to completely remove the repository. Say thanks to this person who made it!

**Comment by vishnu-itachi** [comment]
Hey, sorry to hear about that. Any approx date/time when the repo will be up again?

**Comment by h0tc0d3** [comment]
@vishnu-itachi I don't know yet, nowhere to put the files. I have a local copy and it will take about 5 minutes to deploy. There are about 6 gigabytes of files.

**Comment by vishnu-itachi** [comment]
Any update or any way to get the new updated packages since the site is still down?

**Comment by ptr1337** [comment]
Thinking of providing your repo at my mirrors. Would be 4 mirrors (2 Mirros with 2.5 GBit up both located in Germany, !gbit up Germany, and 1 gbit from Netherlands).

Maybe a solution with syncthing, so you can just provide your repo locally and then will be synced to the server.

**Comment by h0tc0d3** [comment]
I do not use third-party mirrors, for security reasons, so that files and the signature of files are not changed. My signature is written in index.html and install.sh. If the signature changed in them, then new users can be hacked. Also compilation takes a lot of personal time, and it didn’t bring me a single cent, I paid for domains and the cloud from my wallet. I update this repository and have packages for zen2+ and x86_64v3 compiled in my computer. At the moment, I don't know what to do.

**Comment by ptr1337** [comment]
> I do not use third-party mirrors, for security reasons, so that files and the signature of files are not changed. My signature is written in index.html and install.sh. If the signature changed in them, then new users can be hacked. Also compilation takes a lot of personal time, and it didn’t bring me a single cent, I paid for domains and the cloud from my wallet. I update this repository and have packages for zen2+ and x86_64v3 compiled in my computer. At the moment, I don't know what to do.

Thats the reason WHY you get a sync which will use YOUR signing key and your install.sh

**Comment by x0rzavi** [comment]
I really feel sorry to hear that :( Can you take a look at this https://github.com/archcraft-os/packages ? Idk how performant would it be to use github, but archcraft's dev has been using it since archcraft's inception. And as far as I know the os is being used by hundreds if not thousands, I assume this won't be of much trouble. Wishing for the best.

**Comment by ventureoo** [comment]
@x0rzavi As far as I know GitHub allows you to upload files not exceeding 200 MB to the repository, so it's probably not the best solution for large packages.

**Comment by h0tc0d3** [comment]
The update server has been restored!
