### ISSUE TITLE
Arch repo? 

### ISSUE THREAD

**Issue by grigorii-horos** [h0tc0d3/arch-packages#4]
Maybe we can create repo with these packages? I can store files on my server. 
But I think will be better to replace suffix form `-noname` to `-clang`

**Comment by h0tc0d3** [comment]
The idea is good, I'll think about how best to do it. We need to think about which processor optimization we will be doing. I can collect, sign and upload.

**Comment by grigorii-horos** [comment]
Nice! I will wait for any results

**Comment by h0tc0d3** [comment]
I think we can make build for `x86-64-v3`. We have two solutions:
1) We can use same package original name and have pkrel +1. It's have easy instalation and update. But original package after update replace our package.
2) We can use other name and same pkrel. It's have more complicated installation. But update original package can't replace it.

```x86-64: CMOV, CMPXCHG8B, FPU, FXSR, MMX, FXSR, SCE, SSE, SSE2
x86-64-v2: (close to Nehalem) CMPXCHG16B, LAHF-SAHF, POPCNT, SSE3, SSE4.1, SSE4.2, SSSE3
x86-64-v3: (close to Haswell) AVX, AVX2, BMI1, BMI2, F16C, FMA, LZCNT, MOVBE, XSAVE
x86-64-v4: AVX512F, AVX512BW, AVX512CD, AVX512DQ, AVX512VL```

**Comment by h0tc0d3** [comment]
@grigorii-horos I ready to start it and have everything set up. Also added custom glibc and chromium. Please write me in telegram https://t.me/h0tc0d3 or on habr, need access so that I can upload files to your server. Prefer rsync.
