### ISSUE TITLE
Browser has problems with glibc 2.34

### ISSUE THREAD

**Issue by ProFfeSsoRr** [h0tc0d3/arch-packages#7]
https://bugzilla.mozilla.org/show_bug.cgi?id=1715254

Latest chromium din't crash, but telegram and firefox crash. Please rollout glibc to version 2.33.

**Comment by h0tc0d3** [comment]
@ProFfeSsoRr It's not my problem. Official firefox not crash. My telegram not crash. Say thanks for Arch Maintainers who not add patches and not fix bugs in it's own packages. 
I cannot deal with all packages, it takes a long time.

**Comment by h0tc0d3** [comment]
All packages linked with 2.34. Rollback not possible! It can broke all packages.

**Comment by ProFfeSsoRr** [comment]
> @ProFfeSsoRr My telegram not crash

Hm, I tested with your telegram (version from your repo).
Ok, understand your opinion.

**Comment by h0tc0d3** [comment]
@ProFfeSsoRr It's strange. https://archlinux.club/x86_64/ ?

I use telegram every day. Arch Official firefox not crash. Tor Browser 10.5.5 not crash and few day ago they added patches. Slack from flatpack not crash too. Crash only affects arch linux packages.
