### ISSUE TITLE
mangohud does not work with steam-native and steam-runtime

### ISSUE THREAD

**Issue by KuKuRuZ1337** [h0tc0d3/arch-packages#8]
When I write mangohud steam-native or mangohud steam-runtime, steam does not open, although it worked fine before I added it 
p.s. thanks for the repository, chromium clang edition is very fast
![archlinuxclubsteammangohud](https://user-images.githubusercontent.com/65289168/136096029-0c9749d3-c5e4-4429-a302-386542907189.png)
t

**Comment by h0tc0d3** [comment]
@KuKuRuZ1337 I think it's a steam bug and they not added glibc 2.34 compatability. I use glibc 2.34 because it giving better performance with new cpus. Unfortunately rollback to version 2.33 is not possible and will break packages.

**Comment by KuKuRuZ1337** [comment]
> @KuKuRuZ1337 I think it's a steam bug and they not added glibc 2.34 compatability. I use glibc 2.34 because it giving better performance with new cpus. Unfortunately rollback to version 2.33 is not possible and will break packages.

Can Haswell xeon be considered a new processor ?
I was just using the repository for Intel Haswell (is it for haswell ? just that amd zen was mentioned there)
